# Generated by Django 2.2.7 on 2020-08-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20191209_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pizzariaImages')),
                ('image_title', models.CharField(blank=True, max_length=120)),
                ('uploded_at', models.DateTimeField(auto_now_add=True)),
                ('pizzeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzeriaImages', to='stores.Pizzeria')),
            ],
            options={
                'ordering': ['-uploded_at'],
            },
        ),
    ]
