# Generated by Django 2.2.7 on 2020-08-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pizzeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzeria_images', to='stores.Pizzeria'),
        ),
    ]
