# Generated by Django 2.2.7 on 2020-08-06 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200801_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pizzeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzeria_images', to='stores.Pizzeria'),
        ),
    ]
