# Generated by Django 2.2.7 on 2020-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20200806_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='logo_image',
            field=models.ImageField(blank=True, default='https://bit.ly/book-pizza', upload_to='pizzariaImages'),
        ),
    ]
